#!/bin/bash

for $ip in $( gcloud compute instances list | awk '{print $11}'): do
  machinename=$( gcloud compute instances list | grep $ip |awk '{print $2}')
  generate_config.sh $machinename $ip
done

gcloud compute scp *.cfg /etc/nagios/conf.d
