#!/bin/bash

yum -y install rpm-build make gcc git  
mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

cd ~/
echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros 
cd /root/rpmbuild

###Lines 13 and 14 are only if you need to install nrpe and nagioscore### 
###to finish the install and make changes to the source code###

git clone https://github.com/NagiosEnterprises/nrpe.git
git clone https://github.com/NagiosEnterprises/nagioscore.git
