#!/bin/bash

yum -y install rpm-build make gcc git  
mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

cd ~/
echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros 
cd /root/rpmbuild

git clone https://github.com/NagiosEnterprises/nrpe.git
git clone https://github.com/NagiosEnterprises/nagioscore.git
