#!/bin/bash

apt -get install nagios-plugins
apt-get install nagios-nrpe-server

cp /etc/nagios/nrpe.cfg /etc/nagios/nrpe.cfg.bak
sed -i 's/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1, 10.142.0.15/g' /etc/nagios/nrpe.cfg

systemctl restart nagios-nrpe-server


