#!/bin/bash
sed -15i 's/#$ModLoad imudp/$ModLoad imudp/' /etc/rsyslog.conf
sed -16i 's/#$UDPServerRun 514/$UDPServerRun 514/' /etc/rsyslog.conf
sed -19i 's/#$ModLoad imtcp/$ModLoad imtcp/' /etc/rsyslog.conf
sed -20i 's/#$InputTCPServerRun 514/$InputTCPServerRun 514/' /etc/rsyslog.conf

systemctl restart rsyslog.service

yum -y install net-tools
yum -y install logcheck

