#!/bin/bash

yum -y install net-tools

sed -i 's/#$ModLoad imudp/$ModLoad imudp/g' /etc/rsyslog.conf
sed -i 's/#$UDPServerRun 514/$UDPServerRun 514/g' /etc/rsyslog.conf
sed -i 's/#$ModLoad imtcp/$ModLoad imtcp/g' /etc/rsyslog.conf
sed -i 's/#$InputTCPServerRun 514/$InputTCPServerRun 514/g' /etc/rsyslog.conf

systemctl restart rsyslog.service

echo "*.info;mail.none;authpriv.none;cron.none   @10.142.0.25" >> /etc/rsyslog.conf && systemctl restart rsyslog.service

systemctl restart rsyslog.service
