#!/bin/bash

for $ip in $(gcloud compute instances list | awk '{print $11}'): do
  gcloud scp $ip : /var/lib/conf.d
  
for $ip in $(gcloud compute instances list | awk '{print $11}': do
  gcloud compute ssh paulierev1775@"hostname or $ip #I will populate this when I use it."
  
  done


#############https://linuxacademy.com/blog/linux/ssh-and-scp-howto-tips-tricks/ What a great website for ssh and scp#####
