#!/bin/bash

yum -y install rpm-build make gcc git
yum -y install nfs-utils

mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}                     

yum -y install wget
cd ~/

curl https://raw.githubusercontent.com/passwordlandia/nagios/master/startup.spec
wget https://github.com/nic-instruction/hello-NTI-320/startup-0.1.tar.gz
mv startup-0.1.tar.gz\?raw\=true startup-0.1.tar.gz

echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros                        
cd ~/rpmbuild/SOURCES
git clone https://github.com/NagiosEnterprises/nrpe.git                     
git clone https://github.com/NagiosEnterprises/nagioscore.git                

tar -czvf nrpe-3.1.tar.gz /root/rpmbuild/SOURCES/nrpe                        
tar -czvf nagioscore-4.3.1.tar.gz /root/rpmbuild/SOURCES/nagioscore          

mv nagioscore nagioscore-4.3.1                                                
mv nrpe nrpe-3.1                                                             
mkdir nagioscore                                                              
mkdir nrpe
mv nagioscore-4.3.1 nagioscore
mv nrpe-3.1 nrpe

cd ../SPECS                                                                  
cp /usr/share/vim/vimfiles/template.spec .

##############Put in my repo echo line here#####################
